---
- name: Checking system compatibility, please wait...
  when: ansible_distribution != "RedHat"
  fail: msg="THIS IS NOT A SUPPORTED OS, PLEASE ENSURE YOU RUN THIS ON A REDHAT SYSTEM"

- name: Checking RedHat version
  when: ansible_distribution_major_version != "6"
  fail: msg="THIS IS NOT A SUPPORTED REDHAT VERSION. PLEASE ENSURE YOUR USING A RHEL 6 PRODUCT"

### Not needed in production, software not installed via Yum ### 
- name: Installing Java for dependancy 
  yum: name=java-1.8.0-openjdk state=present

- name: Creating the EAP installation directory
  file: path=/app/redhat/jboss/jboss-as-domain mode=0755 state=directory

- name: Copying the JBoss-EAP tarball into /tmp before we extract
  copy: src=jboss-eap.tar.bz2 dest={{ tmp_eap }}
  
- name: Copying the Data Grid modules for EAP into /tmp before we extract
  copy: src=jboss-jdg-modules.tar.bz2 dest={{ tmp_jdgmodules }}

- name: Extracting the archive into the top level JBoss EAP directory
  unarchive: src={{ tmp_eap }} dest={{ extracted_dir }}

- name: Extracting the Data Grid modules archive into the top level JDG directory
  unarchive: src={{ tmp_jdgmodules }} dest={{ extracted_dir }}

- name: Copy the JDG Modules to the JBoss EAP modules directory
  copy: src={{ jdg_modules }} dest={{ eap_jdgmodules }} 

- name: Creating JBoss directory structure
  file: path=/etc/jboss-as state=directory mode=0755

- name: Add JBoss group
  group: name=jboss-as

- name: Add JBoss user and place into the JBoss group
  user: name=jboss-as group=jboss-as home={{ eap_directory }}

- name: Adding the JBoss startup file
  template: src=jboss-as.conf dest=/etc/jboss-as/jboss-as.conf

- name: Fixing JBoss permissions
  file: path=/etc/jboss-as/jboss-as.conf owner=jboss-as mode=0755

- name: Change ownership of JDG modules directory
  file: path={{ jdg_directory }} owner=jboss-as group=jboss-as recurse=yes 

- name: Change ownership of JBoss EAP directory
  file: path=/app/redhat/jboss/jboss-as-domain/jboss-eap-6.4 owner=jboss-as group=jboss-as recurse=yes

- name: Copying in the JBoss domain configuration files
  template: src=domain-6.4.0-twb-2-profiles-v3.xml dest=/app/redhat/jboss/jboss-as-domain/jboss-eap-6.4/domain/configuration/domain-6.4.0-twb-2-profiles-v3.xml

- name: Still copying the JBoss configuration files
  template: src=host01-6.4.0-twb-v3.xml dest=/app/redhat/jboss/jboss-as-domain/jboss-eap-6.4/domain/configuration/host01-6.4.0-twb-v3.xml

- name: Dropping in JBoss init script. Due to Ansible limitations thus far, this is to be run as a service
  template: src=jboss-as-domain.sh dest=/etc/init.d/jboss-as-domain

- name: Setting JBoss EAP permissions
  file: path=/etc/init.d/jboss-as-domain owner=jboss-as mode=0755
  notify: Start JBoss
