---
- name: Checking system compatibility, please wait...
  when: ansible_distribution != "RedHat"
  fail: msg="THIS IS NOT A SUPPORTED OS, PLEASE ENSURE YOU RUN THIS ON A REDHAT SYSTEM"

- name: Checking RedHat version
  when: ansible_distribution_major_version != "6"
  fail: msg="THIS IS NOT A SUPPORTED REDHAT VERSION. PLEASE ENSURE YOUR USING A RHEL 6 PRODUCT"

- name: Creating JBoss host directory structure
  file: path=/etc/jboss-as-host state=directory mode=0755

- name: Adding the JBoss startup file
  template: src=jboss-as-host.conf dest=/etc/jboss-as-host/jboss-as-host.conf

- name: Adding the JBoss init script
  template: src=jboss-as-host.sh dest=/etc/init.d/jboss-as-host

- name: Copying JBoss Host configuration file
  template: src=host02-6.4.0-twb-v3.xml dest=/app/redhat/jboss/jboss-eap-6.4/domain/configuration/host02-6.4.0-twb-v3.xml

- name: Setting JBoss EAP permissions
  file: path=/etc/init.d/jboss-as-host owner=jboss-as mode=0755

- name: Fixing permissions...
  file: path=/etc/jboss-as-host/jboss-as-host.conf owner=jboss-as mode=0755

- name: Still fixing permissions
  file: path=/app/redhat/jboss/jboss-eap-6.4/domain/configuration/host02-6.4.0-twb-v3.xml owner=jboss-as mode=0755

- name: Adding the JBoss user and updating the host02-6.4.0-twb-2-profiles-v3.xml file to include the base64 hash of the password
  shell: /root/BP-Oil-Project/ansible-playbook/roles/jboss-eap-host/files/add-jboss-user.sh
  notify: Start JBoss Host






