---

tmp_eap: /tmp/eap.tar.bz2
extracted_dir: /opt
tmp_jdgmodules: /tmp/datagridmodules.tar.bz2
eap_directory: /opt/jboss-eap-6.4
jdg_directory: /opt/jboss-datagrid-6.5.1-eap-modules-library
jdg_modules: /opt/jboss-datagrid-6.5.1-eap-modules-library/modules/org/infinispan/jdg-6.5
eap_jdgmodules: /opt/jboss-eap-6.4/modules/system/layers/base/org/infinispan


